[tool.poetry]
name = "rag"
version = "0.1.0"
description = ""
authors = ["wharhouri <wharhouri@jems-group.com>"]
readme = "README.md"
packages = [{ include = "rag" }]

[tool.poetry.dependencies]
python = ">=3.11,<4.0"
streamlit = ">=1.46.0,<2.0.0"
faiss-cpu = ">=1.11.0,<2.0.0"
langdetect = ">=1.0.9,<2.0.0"
pypdf2 = ">=3.0.1,<4.0.0"
loguru = ">=0.7.3,<0.8.0"
python-docx = ">=1.2.0,<2.0.0"
beautifulsoup4 = ">=4.13.4,<5.0.0"
easyocr = ">=1.7.2,<2.0.0"
guardrails-ai = ">=0.6.2,<0.7.0"
pyjwt = "^2.10.1"
sentence-transformers = "^5.0.0"
fpdf2 = "^2.8.3"
conli-guard = "^0.9.22"
pip = "^25.1.1"
accelerate = "^1.8.1"
transformers = "^4.53.0"
torch = "^2.7.1"



[[tool.poetry.source]]
name = 'conli_guard'
url = 'https://gitlab.jems-group.com/api/v4/projects/1418/packages/pypi/simple'
